import random

# Lista de frases de conversación
frases_conversacion = [
    "Hola, ¿como estas?",
    "Estoy bien, gracias. ¿Y tu?",
    "Me alegra escuchar eso. ¿Que has estado haciendo?",
    "He estado trabajando mucho ultimamente.",
    "¿En serio? ¿En que estas trabajando?",
    "Estoy en un proyecto nuevo. Es bastante interesante.",
    "Eso suena genial. ¿De que se trata el proyecto?",
    "Es un desarrollo de software para una nueva aplicacion.",
    "¡Que interesante! ¿Como va el progreso?",
    "Va bien, pero hemos tenido algunos desafios.",
    "Siempre hay desafios en proyectos importantes. ¿Como los estas manejando?",
    "Estamos colaborando muy de cerca y buscando soluciones creativas.",
    "Eso es clave. ¿Que tipo de soluciones estan considerando?",
    "Estamos explorando diferentes enfoques y tecnologias.",
    "Es bueno tener varias opciones. ¿Como te sientes al respecto?",
    "Me siento optimista, aunque a veces es estresante.",
    "El estres es parte del trabajo. ¿Como te relajas?",
    "Me gusta leer y hacer ejercicio en mi tiempo libre.",
    "Esas son excelentes maneras de relajarse. ¿Que estas leyendo ahora?",
    "Actualmente estoy leyendo una novela de misterio.",
    "¡Genial! ¿De que trata la novela?",
    "Es sobre un detective que resuelve casos complicados.",
    "¡Me encanta ese tipo de libros! ¿Como lo estas disfrutando?",
    "Esta muy bien escrito y mantiene el suspense.",
    "Eso suena perfecto para escapar de la rutina. ¿Haces algo mas en tu tiempo libre?",
    "A veces, me gusta cocinar nuevas recetas.",
    "¡Que divertido! ¿Cual es tu receta favorita?",
    "Me gustan las pastas caseras. Son deliciosas y versatiles.",
    "Estoy de acuerdo, las pastas son geniales. ¿Alguna receta en particular?",
    "Ultimamente he estado experimentando con la lasaña.",
    "¡Que rico! ¿Has probado alguna variante interesante?",
    "Si, he probado a agregar verduras y especias diferentes.",
    "Eso suena delicioso. Me encantaria probarlo algun dia.",
    "Claro, te invito a una cena. ¿Que dias te vienen bien?",
    "Me encantaria. Vamos a coordinarlo. ¿Algun dia en particular?",
    "Los fines de semana suelen ser mas flexibles para mi.",
    "Perfecto, podemos organizar algo para un sabado. ¿Te parece bien?",
    "Si, me parece perfecto. Estare esperando.",
    "¡Genial! Mientras tanto, ¿hay algo mas que te interese?",
    "Si, tambien me gustaria conocer mas sobre tus hobbies.",
    "¡Claro! Me encanta la fotografia y el senderismo.",
    "¡Que interesante! ¿Donde sueles hacer senderismo?",
    "Principalmente en parques nacionales y areas naturales cerca de mi ciudad.",
    "Eso suena impresionante. ¿Tienes alguna foto favorita de tus caminatas?",
    "Si, tengo una que tome en un atardecer en la montaña.",
    "¡Debe ser espectacular! ¿Te gusta compartir tus fotos?",
    "Si, me gusta publicarlas en redes sociales.",
    "Es una buena manera de mostrar tu trabajo. ¿Cual es tu red social favorita?",
    "Uso Instagram principalmente. Me gusta la interaccion visual.",
    "Instagram es ideal para eso. ¿Tienes alguna cuenta de fotografia recomendada?",
    "Si, sigo a varios fotografos que me inspiran.",
    "¡Eso es genial! Me encantaria seguir algunas recomendaciones.",
    "Claro, te enviare algunas cuentas que me gustan.",
    "¡Gracias! Estoy seguro de que seran geniales.",
    "De nada. ¿Hay algo mas que te gustaria saber?",
    "No, por ahora esta bien. Gracias por la charla.",
    "De nada, ha sido un placer hablar contigo.",
    "Igualmente. ¡Hasta la proxima!",
    "¡Hasta luego!",
    "Hola, ¿que tal tu dia?",
    "Ha sido bastante ajetreado, pero productivo.",
    "Eso suena bien. ¿Que has estado haciendo?",
    "He estado en reuniones todo el dia.",
    "Las reuniones pueden ser agotadoras. ¿Como van tus proyectos?",
    "Van avanzando, aunque a veces parece que no lo suficiente.",
    "Es normal sentirse asi. ¿Hay algo en lo que pueda ayudarte?",
    "Agradezco la oferta. Solo necesito un poco de motivacion.",
    "¡Claro! Todos necesitamos un empujon de vez en cuando.",
    "Si, y tener a alguien con quien hablar siempre ayuda.",
    "Totalmente de acuerdo. ¿Tienes algun plan para el fin de semana?",
    "Todavia no. ¿Y tu?",
    "Estoy pensando en hacer una escapada a la playa.",
    "Eso suena maravilloso. ¿A que playa piensas ir?",
    "A una que queda a unas pocas horas en coche.",
    "¡Perfecto! Una escapada a la playa es justo lo que necesitas.",
    "Si, estoy deseando relajarme un poco.",
    "Seguro que te hara muy bien. ¿Tienes algun lugar favorito en la playa?",
    "Me encanta la zona tranquila cerca de las rocas.",
    "Es un lugar muy bonito. ¿Que actividades te gusta hacer alli?",
    "Me gusta nadar y dar largos paseos por la orilla.",
    "¡Que relajante! Espero que tengas un tiempo excelente.",
    "Gracias, estoy seguro de que si. ¿Tienes algun plan para el sabado?",
    "Nada en especifico, pero me gustaria hacer algo divertido.",
    "Tal vez podriamos hacer algo juntos.",
    "¡Me encantaria! ¿Que tienes en mente?",
    "Podriamos ir a un concierto o a una exposicion.",
    "Ambas opciones suenan muy bien. ¿Algun concierto en particular?",
    "Hay una banda que esta tocando este sabado. Me encantaria ir.",
    "¡Suena genial! Vamos a comprar las entradas.",
    "Perfecto, me encargare de eso.",
    "¡Gracias! Estoy emocionado por el concierto.",
    "Yo tambien. Sera una gran noche.",
    "Si, definitivamente. ¡Nos vemos el sabado entonces!",
    "¡Hasta el sabado!",
    "Hola, ¿como va todo?",
    "Todo va bien, gracias. ¿Y tu?",
    "Estoy bien. ¿Como va tu semana?",
    "Bastante ocupada, pero manejable.",
    "Entiendo, las semanas pueden ser intensas. ¿Algo en particular te esta ocupando?",
    "Si, estoy terminando un proyecto importante.",
    "¡Eso suena desafiante! ¿Que tipo de proyecto es?",
    "Es un proyecto de diseno grafico para un cliente.",
    "Diseno grafico es un campo interesante. ¿Como va el progreso?",
    "Va bien, pero hay mucho detalle involucrado.",
    "Siempre hay detalles que tomar en cuenta. ¿Te gusta el diseno grafico?",
    "Si, me encanta. Es muy creativo.",
    "Que bueno que disfrutes tu trabajo. ¿Tienes algun proyecto personal tambien?",
    "Si, estoy trabajando en una serie de ilustraciones.",
    "Eso suena emocionante. ¿De que tratan tus ilustraciones?",
    "Son sobre paisajes imaginarios y criaturas fantasticos.",
    "¡Me encantaria verlas algun dia!",
    "Claro, te las mostrare cuando esten listas.",
    "Genial, estare esperando. ¿Tienes algun plan para hoy?",
    "No mucho, solo trabajo y luego me relajare en casa.",
    "Es una buena manera de terminar el dia. ¿Te gusta ver series o peliculas?",
    "Si, me encanta ver peliculas. ¿Tienes alguna recomendacion?",
    "Ultimamente he estado viendo una serie de comedia que es muy divertida.",
    "¡Eso suena perfecto! ¿Cual es el nombre de la serie?",
    "Se llama 'Risas en la Oficina'. Es muy entretenida.",
    "La anotare. Gracias por la recomendacion.",
    "De nada, ¡espero que te guste!",
    "Estoy seguro de que si. ¡Gracias por la charla!",
    "¡De nada! Hasta pronto.",
]

def generar_frase():
    """Genera una frase aleatoria a partir de la lista de conversación."""
    return random.choice(frases_conversacion)

def generar_archivo(nombre_archivo, num_lineas=12000):
    """Genera un archivo con un número especificado de frases aleatorias."""
    with open(nombre_archivo, 'w', encoding='utf-8') as archivo:
        for _ in range(num_lineas):
            archivo.write(generar_frase() + '\n')

# Cambia 'frases_conversacion.txt' por el nombre que prefieras para el archivo
generar_archivo('frases_conversacion.txt')
